on:
  push:
    branches:
      - main
name: 🚀 Deploy website on push (Main)
jobs:
  deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          tools: phpmd
          extensions: pdo, pdo_mysql, mbstring, tokenizer, xml, ctype, json, fileinfo

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress
      
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      
      - name: Generate key
        run: |
         php artisan config:clear
         php artisan cache:clear
         php artisan key:generate
      
      - name: Generate storage link
        run: php artisan storage:link

      - name: Directory Pernmissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Run Unit tests
        env:
          APP_ENV: testing
          DB_CONNECTION: mysql
          DB_USERNAME: doubleki_admin
          DB_PASSWORD: y{z,v]Eklwm{
          DB_DATABASE: doubleki_realestate
        run: php artisan test

      - name: 📂 Sync files
        if: ${{ success() }}
        uses: SamKirkland/FTP-Deploy-Action@master
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /
