name: Test and Deploy Real Estate Web App

on:
  push:
    branches:
      - main

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: 0991chinweNDU1990
          MYSQL_DATABASE: doubleki_realestate_db
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3


    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.2'
        
    - uses: actions/checkout@v4
    
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      
    - name: Generate key
      run: |
       php artisan config:clear
       php artisan cache:clear
       php artisan optimize
       php artisan key:generate
      
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache

    - name: Run migrations
      env:
        DB_CONNECTION: mysql
        DB_HOST: 127.0.0.1
        DB_PORT: 3306
        DB_DATABASE: doubleki_realestate_db
        DB_USERNAME: doubleki_db_admin
        DB_PASSWORD: 0991chinweNDU1990
      run: |
        php artisan migrate --force
        php artisan db:seed --force
      
    - name: Execute tests 
      run: php artisan test

  deploy:

    runs-on: ubuntu-latest

    needs: laravel-tests

    steps:
    - uses: actions/checkout@v4

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@master
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: /
